default_install_hook_types: [pre-commit, post-commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: file-contents-sorter
        args: [--unique]
        files: ^\.gitattributes$|^\.gitignore$|^requirements-dev\.txt$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: new-version-tag
        name: new version tag
        entry: python ./new_version_tag.py
        stages: [post-commit]
        always_run: true
        language: python
        additional_dependencies: ["tomlkit>=0.13"]
